# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s="Hi there Sam!"
word=s.split()
print(word)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
plant="Earth"
diameter=12742
print('The diameter of {} is {} kilometer.'.format(plant,diameter));

The diameter of Earth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3]) 

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
arr=np.arange(20,36,2)
print(arr)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8])
a.resize(3,3)
print(a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 



## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
import pandas as pd 
array=np.array([['ramya',20],['mohanapriya',19],['mohana',20]])
index_values=['A','B','C']
column_values=['Name','Age']
df=pd.DataFrame(data=array,index=index_values,columns=column_values)
print(df)

          Name Age
A        ramya  20
B  mohanapriya  19
C       mohana  20


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
dt_series=pd.Series(['1st Jan,2023','10th Feb,2023'])
print('series of data strings:')
print(dt_series)
print(dt_series)


series of data strings:
0     1st Jan,2023
1    10th Feb,2023
dtype: object
0     1st Jan,2023
1    10th Feb,2023
dtype: object


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(lists,columns=['Number','Alphabet','Age'])
print(df)


   Number Alphabet  Age
0       1      aaa   22
1       2      bbb   25
2       3      ccc   24
